language: python
cache: pip
sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install codecov

script:
  - nosetests -v --cover-package=pytaxa

after_success:
  - codecov
